### ISSUE TITLE
RX 系列經測試可用

### ISSUE THREAD

**Issue by clspeter** [PhantasWeng/panasonic_smart_app#5]
RX 系列可用
已測試型號
CS-RX28GA2
CS-RX36GA2
CS-RX50GA2
CS-RX71GA2

**Comment by PhantasWeng** [comment]
感謝協助測試👍🏻

**Comment by joe091500** [comment]
感謝分享~
終於把空調給整合到HOMEKIT了
CS-J68BDA2
CS-J28BDA2
CS-J22BDA2
測試可用
可惜一點是若用遙控器操作後，空調狀態要2-3分鐘才會回饋到Home Assistant上

感謝您

**Comment by PhantasWeng** [comment]
> 終於把空調給整合到HOMEKIT了

感謝測試，我再把他補到說明去
關於要等待回饋，這是因為API的關係
目前無法官方的APP中拿不到狀態主動變更，如果太頻繁詢問可能會有被封鎖的風險
不過你給了我一個不錯的Idea，我可以嘗試拿APP開關機的時候的通知來做更新Hook
