### ISSUE TITLE
Missing 'version' key in the manifest.json

### ISSUE THREAD

**Issue by stev3nw** [PhantasWeng/panasonic_smart_app#6]
Hi
As of Home Assistant 2021.6, custom integration without version key in manifest.json would no longer be loaded.

Related Informations:
[Breaking Changes on HA 2021.6](https://www.home-assistant.io/blog/2021/06/02/release-20216/#other-breaking-changes)
[Developer Blog](https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes/#versions)
[Block custom integrations with missing or invalid version](https://github.com/home-assistant/core/pull/49916)

**Comment by PhantasWeng** [comment]
#7

**Comment by PhantasWeng** [comment]
@Esvent,  Done in #7, and update version to v0.1.4, need help for testing. Please update your integration to v0.1.4.

**Comment by stev3nw** [comment]
Hi,
Confirmed this issue is resolved in v0.1.4 with Home Assistant core-2021.6.3.
Thank you!
