### ISSUE TITLE
中國區的homeassistant panasonic smart能煩勞適配下麽

### ISSUE THREAD

**Issue by SparkCD** [PhantasWeng/panasonic_smart_app#9]
**_嘿你好  中國區的homeassistant panasonic smart能煩勞適配下麽 如果需要提供什麽  我會盡快回復_**

**Comment by PhantasWeng** [comment]
目前我沒有任何朋友能夠協助我中國的測試
所以沒辦法開發

但歡迎 Fork 我的專案去修改
